[advisories]
ignore = []

[licenses]
include-dev = true
allow = ["Apache-2.0", "MIT", "Unicode-3.0", "MPL-2.0"]
confidence-threshold = 0.9

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
