//! Test driver only: trusts synthetic fixture enrollment supplied on stdin.
//! Not an agent API, user enrollment ceremony or production mandate generator.
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use std::{
    io::{Read, Write},
    path::PathBuf,
    time::{Duration, Instant},
};
use vollmacht_helper_probe::{Coordinator, Failure, Launch, MAX_BODY, Request};

fn run() -> Result<(), ()> {
    let args: Vec<_> = std::env::args_os().skip(1).take(4).collect();
    if args.len() != 3 {
        return Err(());
    }
    let mut nonce = [0; 32];
    let mut id = [0; 16];
    getrandom::fill(&mut nonce).map_err(|_| ())?;
    getrandom::fill(&mut id).map_err(|_| ())?;
    let mut digest = openssl::sha::Sha256::new();
    digest.update(b"vollmacht:experimental:webauthn-binding:v1\0");
    digest.update(&nonce);
    digest.update(b"{\"action\":\"simulate_merge\",\"pr\":42}");
    let challenge = URL_SAFE_NO_PAD.encode(digest.finish());
    let request_id: String = id.iter().map(|b| format!("{b:02x}")).collect();
    println!(
        "{}",
        serde_json::json!({"challenge":challenge,"request_id":request_id})
    );
    std::io::stdout().flush().map_err(|_| ())?;
    let mut bytes = Vec::new();
    std::io::stdin()
        .take((MAX_BODY + 1) as u64)
        .read_to_end(&mut bytes)
        .map_err(|_| ())?;
    let request = Request::parse(&bytes).map_err(|_| ())?;
    let fields: serde_json::Value = serde_json::from_slice(&bytes).map_err(|_| ())?;
    // Fixture cannot overwrite the expected binding generated by Rust.
    if fields["challenge"] != challenge || fields["request_id"] != request_id {
        return Err(());
    }
    let coordinator = Coordinator::new(request, Instant::now() + Duration::from_secs(5));
    let launch = Launch {
        executable: PathBuf::from(&args[0]),
        launcher: PathBuf::from(&args[1]),
        helper: Some(PathBuf::from(&args[2])),
        directory: std::env::current_dir().map_err(|_| ())?,
    };
    let result = coordinator.verify(launch.clone());
    let outcome = match result {
        Ok(_) => "verified",
        Err(Failure::VerificationRejected) => "rejected",
        Err(_) => "harness_error",
    };
    let replay_denied = coordinator.verify(launch) == Err(Failure::CeremonyUnavailable);
    println!(
        "{}",
        serde_json::json!({"outcome":outcome,"replay_denied":replay_denied})
    );
    Ok(())
}

fn main() {
    if run().is_err() {
        std::process::exit(1);
    }
}
